on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - 'pypy3.10'
        coverage:
          - '6.0'
          - '7.0'
    name: Python ${{ matrix.python }} on coverage ${{ matrix.coverage }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install setuptools coverage==${{ matrix.coverage}} && pip install . && pip install -r requirements-dev.txt
      - name: Run tests
        run: python -m pytest
